/**
 * MultiMode MapCycle Configuration Keys
 * 
 * Defines for all map cycle configuration keys.
 */

#if defined _multimode_mapcyclecommands_included
 #endinput
#endif
#define _multimode_mapcyclecommands_included

// Map Cycle Configuration Keys
#define MAPCYCLE_KEY_COMMAND           "command"
#define MAPCYCLE_KEY_PRE_COMMAND       "pre-command"
#define MAPCYCLE_KEY_VOTE_COMMAND      "vote-command"
#define MAPCYCLE_KEY_DISPLAY           "display"
#define MAPCYCLE_KEY_CONFIG            "config"
#define MAPCYCLE_KEY_NOMINATE_FLAGS    "nominate_flags"
#define MAPCYCLE_KEY_MINTIME           "mintime"
#define MAPCYCLE_KEY_MAXTIME           "maxtime"
#define MAPCYCLE_KEY_MINPLAYERS        "minplayers"
#define MAPCYCLE_KEY_MAXPLAYERS        "maxplayers"
#define MAPCYCLE_KEY_MAPS_INVOTE       "maps_invote"
#define MAPCYCLE_KEY_SUBGROUPS_INVOTE  "subgroups_invote"
#define MAPCYCLE_KEY_WEIGHT            "weight"

// Map Cycle Actions Keys
#define MAPCYCLE_KEY_ACTIONS                   "actions"
#define MAPCYCLE_ACTION_WARNING_CHAT           "warning_chat"
#define MAPCYCLE_ACTION_WARNING_CENTER         "warning_center"
#define MAPCYCLE_ACTION_WARNING_HINT           "warning_hint"
#define MAPCYCLE_ACTION_WARNING_CUSTOM         "warning_custom"
#define MAPCYCLE_ACTION_CHANGE_VOTEMANAGER     "change_votemanager"


